/// <reference types="vite/client" />

type ProjectNode = { name: string; path: string; kind: "file" | "folder"; children?: ProjectNode[] };
type OpenProject = { name: string; path: string; files: ProjectNode[]; packageInfo?: { scripts?: Record<string, string>; [key: string]: unknown } | null };
type OpenFile = { path: string; content: string; modifiedAt: number };
type SearchResult = { path: string; line: number; preview: string };
type GitSummary = { repository: boolean; branch: string | null; changes: Array<{ status: string; path: string }> };
type GitOperationResult = { code: number; stdout: string; stderr: string; action: string; status: string; conflicts: string[] };
type CommandResult = { code: number; stdout: string; stderr: string; command: string };
type PreviewState = { running: boolean; url: string | null; logs: string[]; command: string | null };
type PreviewElementReference = {
  key: string; tag: string; id: string; classes: string[]; text: string; selector: string;
  attributes: Record<string, string>; rect: { x: number; y: number; width: number; height: number };
  path: string | null; startLine: number | null; endLine: number | null; label: string;
  confidence: "high" | "medium" | "low" | "unresolved";
};
type NoteAsset = { path: string; markdownPath: string; mime: string; size: number };
type SystemBenchmarkReport = {
  generatedAt: string;
  system: { os: string; arch: string; cpu: string; logicalCores: number; totalMemoryMb: number; freeMemoryMb: number; gpu: string };
  measured: { durationMs: number; cpuOpsPerSecond: number; memoryCopyMbps: number; diskWriteMbps: number; diskReadMbps: number; appRamStartMb: number; appRamPeakMb: number };
  assessment: { level: "ideal" | "good" | "limited"; label: string; summary: string; reasons: string[] };
  estimates: Array<{ scenario: string; minimumRamMb: number; typicalRamMb: number; peakRamMb: number; typicalCpuPercent: number; peakCpuPercent: number; note: string }>;
  recommendations: string[];
};
type WorkspaceProject = { id: string; name: string; path: string; createdAt: string; lastOpenedAt: string };
type ConversationMeta = { id: string; projectPath: string; projectName: string; title: string; kind: "agent" | "chat"; createdAt: string; updatedAt: string };
type WorkspaceIndex = { projects: WorkspaceProject[]; conversations: ConversationMeta[]; activeProjectPath: string | null };
type SavedConversation = ConversationMeta & { data: Record<string, unknown> };
type ConnectorInput = { kind: "api" | "local" | "cli"; url: string; token: string; model: string; temperature?: number; maxTokens?: number | null };
type ConnectorState = { configured: boolean; kind?: string; url?: string; model?: string };
type ModelProfile = { id: string; name: string; provider: string; kind: string; url: string; endpoint: string; model: string; temperature: number; maxTokens?: number | null; testedAt: string; hasStoredToken: boolean; builtIn?: boolean; available?: boolean; baseModelId?: string | null; baseModelName?: string | null };
type ModelRouting = { mode: "single" | "team"; primary: string | null; build: string | null; review: string | null; orchestrate: string | null; reviewPasses: number; fallbackOrder: string[] };
type ModelsState = { models: ModelProfile[]; activeModelId: string | null; routing: ModelRouting };
type DamaSettings = {
  onboardingCompleted: boolean;
  profile: { name: string; useCase: string; experience: string };
  agent: { defaultMode: string; approvalPolicy: string; limitTurns: boolean; maxTurns: number; sendOnEnter: boolean; language: string; temperature: number; contextWindow: number; connectionRetries: number; formatRetries: number; customInstructions: string };
  privacy: { telemetry: boolean; diagnostics: boolean; localHistory: boolean };
  notifications: { enabled: boolean; approvals: boolean; completion: boolean; onlyWhenUnfocused: boolean; longRunSeconds: number };
  updates: { automatic: boolean; checkOnStartup: boolean; channel: "stable" | "beta" };
  appearance: { density: string; motion: boolean; contextPanel: boolean; accent: string; surface: string; scale: number };
  remote: { appUrl: string };
  damaEngine: { baseModelId: string | null };
  computerUse: { enabled: boolean };
  projectMemory: { enabled: boolean };
  mcpServers: Array<{ id: string; name: string; transport: "stdio" | "http"; command?: string; args?: string; url?: string; enabled: boolean }>;
  plugins: Array<{ id: string; name: string; version: string; description?: string; path: string; enabled: boolean }>;
};
type UpdateState = {
  supported: boolean;
  status: "idle" | "checking" | "available" | "downloading" | "downloaded" | "installing" | "current" | "error" | "unsupported";
  currentVersion: string;
  version: string | null;
  releaseName: string | null;
  releaseNotes: string;
  releaseDate: string | null;
  percent: number;
  transferred: number;
  total: number;
  bytesPerSecond: number;
  automatic: boolean;
  error: string | null;
  postUpdate: { version: string; previousVersion: string | null; releaseName: string; releaseNotes: string; releaseDate: string | null } | null;
  rollbackStatus: "idle" | "checking" | "downloading" | "ready" | "error";
  rollbackPercent: number;
  rollbackError: string | null;
};
type DamaQuota = { limit: number; used: number; remaining: number; percentage: number; exhausted: boolean; cycleStartedAt: string; renewsAt: string; updatedAt: string; unit: "tokens"; enforcement: "local" };
type DamaEngineInstallProgress = { status: "idle" | "checking" | "downloading" | "verifying" | "installing" | "done" | "error"; percent: number; detail: string; error: string | null };
type DamaEngineStatus = {
  id: string;
  installed: boolean;
  verified: boolean | null;
  version: string | null;
  source: string;
  features: string[];
  location: string | null;
  message: string;
  quota: DamaQuota;
};
type RemoteState = {
  enabled: boolean;
  status: "off" | "starting" | "downloading" | "ready" | "error";
  endpoint: string | null;
  localPort: number | null;
  connected: boolean;
  lastSeenAt: string | null;
  pairingUrl: string | null;
  qrDataUrl: string | null;
  error: string | null;
  mode: "internet" | "local";
  detail?: string | null;
};
type Plan = {
  title: string;
  summary: string;
  steps: Array<{ title: string; detail: string; files?: string[] }>;
  commands?: Array<{ command: string; reason: string }>;
  risks?: string[];
};
type AgentPreparation = { mode: "direct" | "plan"; intro: string; plan: Plan; standalone?: boolean; conversation?: boolean };
type ChangeSetSummary = { id: string; status: "pending" | "accepted" | "rejected"; createdAt: string; projectPath: string; added: number; removed: number; files: Array<{ path: string; added: number; removed: number; created: boolean }> };
type ChangeDiff = { path: string; added: number; removed: number; lines: Array<{ kind: "same" | "added" | "removed" | "skip"; oldLine: number | null; newLine: number | null; content: string }> };
type ChangeSetResolution = { changeSet: ChangeSetSummary; project: OpenProject; git: GitSummary };
type AgentResult = { summary: string; changedFiles: string[]; reviewRounds?: number; changeSet?: ChangeSetSummary | null; project: OpenProject | null; git: GitSummary };
type AgentProgressEvent = {
  id: string;
  runId: string;
  at: string;
  stage: "planning" | "execution";
  type: "status" | "tool" | "commentary" | "message" | "done" | "error";
  title: string;
  detail: string;
  state: "running" | "done" | "error";
};
type ToolApprovalDecision = "deny" | "once" | "chat" | "project" | "global";
type ToolApprovalRequest = {
  id: string;
  runId: string;
  chatId: string | null;
  projectPath: string | null;
  tool: string;
  title: string;
  detail: string;
  risk: string;
  at: string;
  status?: "pending" | "approved" | "denied";
  decision?: ToolApprovalDecision;
};

interface Window {
  dama?: {
    apiVersion?: number;
    openProject: () => Promise<OpenProject | null>;
    selectProject: (projectPath: string) => Promise<OpenProject>;
    createProjectFromPrompt: (prompt: string) => Promise<OpenProject>;
    listWorkspace: () => Promise<WorkspaceIndex>;
    saveConversation: (payload: ConversationMeta & { data: Record<string, unknown> }) => Promise<ConversationMeta>;
    loadConversation: (id: string) => Promise<SavedConversation | null>;
    deleteConversation: (id: string) => Promise<boolean>;
    refreshProject: () => Promise<OpenProject>;
    readFile: (relativePath: string) => Promise<OpenFile>;
    writeFile: (relativePath: string, content: string) => Promise<{ path: string; modifiedAt: number }>;
    createFile: (relativePath: string) => Promise<OpenProject>;
    createNote: (title: string) => Promise<{ project: OpenProject; file: OpenFile }>;
    importNoteAsset: (payload: { notePath: string; name: string; mime: string; data: Uint8Array }) => Promise<NoteAsset>;
    readNoteAsset: (relativePath: string) => Promise<{ path: string; mime: string; dataUrl: string }>;
    runSystemBenchmark: () => Promise<SystemBenchmarkReport>;
    searchProject: (query: string) => Promise<SearchResult[]>;
    gitSummary: () => Promise<GitSummary>;
    gitDiff: (relativePath?: string) => Promise<string>;
    gitInit: () => Promise<GitSummary>;
    gitOperation: (input: Record<string, unknown>) => Promise<GitOperationResult>;
    runCommand: (command: string) => Promise<CommandResult>;
    startCommand: (command: string, id: string) => Promise<{ id: string; command: string }>;
    stopCommand: (id: string) => Promise<boolean>;
    onTerminalEvent: (callback: (event: { id: string; command: string; type: "output" | "error" | "exit"; stream?: "stdout" | "stderr"; data?: string; code?: number }) => void) => () => void;
    startPreview: () => Promise<PreviewState>;
    stopPreview: () => Promise<PreviewState>;
    previewStatus: () => Promise<PreviewState>;
    enablePreviewInspector: (url: string) => Promise<{ active: boolean; selected: unknown[]; loading?: boolean }>;
    previewInspectorState: (url: string) => Promise<{ active: boolean; selected: unknown[]; loading?: boolean }>;
    getPreviewSelection: (url: string) => Promise<PreviewElementReference[]>;
    clearPreviewInspector: (url: string) => Promise<{ active: boolean; selected: unknown[]; loading?: boolean }>;
    disablePreviewInspector: (url: string) => Promise<{ active: boolean; selected: unknown[]; loading?: boolean }>;
    onPreviewUpdate: (callback: (state: PreviewState) => void) => () => void;
    setConnector: (config: ConnectorInput) => Promise<ConnectorState>;
    clearConnector: () => Promise<ConnectorState>;
    testConnector: () => Promise<{ ok: boolean; latencyMs: number; response: string }>;
    listModels: () => Promise<ModelsState>;
    testAndSaveModel: (config: ConnectorInput & { id?: string; name: string; provider: string }) => Promise<{ ok: boolean; latencyMs: number; model: ModelProfile; activeModelId: string; routing: ModelRouting }>;
    testModel: (id: string) => Promise<{ ok: boolean; latencyMs: number; testedAt: string }>;
    setActiveModel: (id: string) => Promise<{ activeModelId: string; routing: ModelRouting }>;
    updateModelRouting: (routing: ModelRouting) => Promise<ModelRouting>;
    removeModel: (id: string) => Promise<ModelsState>;
    getSettings: () => Promise<DamaSettings>;
    updateSettings: (patch: Partial<DamaSettings>) => Promise<DamaSettings>;
    resetOnboarding: () => Promise<DamaSettings>;
    getUpdateState: () => Promise<UpdateState>;
    checkForUpdates: () => Promise<UpdateState>;
    downloadUpdate: () => Promise<UpdateState>;
    installUpdate: () => Promise<boolean>;
    acknowledgeUpdate: () => Promise<UpdateState>;
    rollbackUpdate: () => Promise<UpdateState>;
    onUpdateState: (callback: (state: UpdateState) => void) => () => void;
    onNotificationOpen: (callback: (state: { target: "agent" }) => void) => () => void;
    getRemoteState: () => Promise<RemoteState>;
    startRemote: () => Promise<RemoteState>;
    stopRemote: () => Promise<RemoteState>;
    onRemoteState: (callback: (state: RemoteState) => void) => () => void;
    onConversationChanged: (callback: (payload: { id: string; source: "remote" }) => void) => () => void;
    onRemoteAgentMessage: (callback: (payload: { conversationId: string; message: AgentThreadMessage }) => void) => () => void;
    damaEngineStatus: (verify?: boolean) => Promise<DamaEngineStatus>;
    damaQuotaStatus: () => Promise<DamaQuota>;
    onDamaQuota: (callback: (state: DamaQuota) => void) => () => void;
    onDamaEngineInstallProgress: (callback: (state: DamaEngineInstallProgress) => void) => () => void;
    installDamaEngine: () => Promise<DamaEngineStatus>;
    removeDamaEngine: () => Promise<DamaEngineStatus>;
    setDamaEngineBaseModel: (id: string | null) => Promise<ModelsState>;
    clearToolApprovals: () => Promise<boolean>;
    listPendingToolApprovals: () => Promise<ToolApprovalRequest[]>;
    chooseLocalPlugin: () => Promise<DamaSettings["plugins"][number] | null>;
    createPlan: (prompt: string, modelId?: string | null, reasoning?: string, runId?: string, history?: Array<{ role: "user" | "assistant"; content: string }>, forcePlan?: boolean) => Promise<AgentPreparation>;
    revisePlan: (payload: { originalPrompt: string; instruction: string; plan: Plan; modelId?: string | null; reasoning?: string; runId?: string; history?: Array<{ role: "user" | "assistant"; content: string }> }) => Promise<Plan>;
    executePlan: (payload: { prompt: string; plan: Plan; modelId?: string | null; reasoning?: string; runId?: string; conversationId?: string | null; history?: Array<{ role: "user" | "assistant"; content: string }>; direct?: boolean; baseChangeSetId?: string | null }) => Promise<AgentResult>;
    getChangeSet: (id: string) => Promise<ChangeSetSummary>;
    getChangeDiff: (id: string, relativePath: string) => Promise<ChangeDiff>;
    acceptChangeSet: (id: string) => Promise<ChangeSetResolution>;
    rejectChangeSet: (id: string) => Promise<ChangeSetResolution>;
    steerAgent: (runId: string, message: string) => Promise<{ accepted: boolean }>;
    onAgentEvent: (callback: (event: AgentProgressEvent) => void) => () => void;
    resolveToolApproval: (id: string, decision: ToolApprovalDecision) => Promise<boolean>;
    onToolApproval: (callback: (request: ToolApprovalRequest) => void) => () => void;
    chat: (payload: { messages: Array<{ role: "user" | "assistant"; content: string }>; modelId?: string | null; reasoning: string }) => Promise<{ content: string; model?: string | null }>;
    openExternal: (url: string) => Promise<void>;
    copyText: (value: string) => Promise<boolean>;
    platform: string;
  };
}
